version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt

linters:
  default: standard
  enable:
    - revive
    - gosec
  settings:
    revive:
      rules:
        - name: blank-imports
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
