FROM golang:1.27.1-trixie AS builder

RUN CGO_ENABLED=0 go install github.com/rubenv/sql-migrate/sql-migrate@v1.8.1

FROM alpine:3.24.2

RUN apk add --no-cache \
    postgresql18-client \
    curl

WORKDIR /migrations

COPY --from=builder /go/bin/sql-migrate /usr/local/bin/sql-migrate
COPY dbconfig.yml .
COPY migrations ./migrations

ENTRYPOINT [ "sleep", "infinity" ]
