// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateImageRequest defines model for CreateImageRequest.
type CreateImageRequest struct {
	// Name Name of the image.
	Name string `json:"name"`

	// Seed Seed for procedural generation. Stored server-side for possible
	// regeneration, never returned to clients.
	Seed int `json:"seed"`
}

// Error Uniform error payload.
type Error struct {
	Error struct {
		// Message Error description.
		Message string `json:"message"`
	} `json:"error"`
}

// ImageMeta Metadata of a stored image. The seed used for generation is
// deliberately not exposed.
type ImageMeta struct {
	// CreatedAt Creation timestamp in UTC.
	CreatedAt time.Time `json:"created_at"`

	// Name Name of the image.
	Name string `json:"name"`

	// Uuid Stable identifier of the image.
	Uuid openapi_types.UUID `json:"uuid"`
}

// ListImagesResponse defines model for ListImagesResponse.
type ListImagesResponse struct {
	Items []ImageMeta `json:"items"`

	// Limit Applied page size.
	Limit int `json:"limit"`

	// Offset Applied offset.
	Offset int `json:"offset"`

	// Total Total number of images available.
	Total int `json:"total"`
}

// UpdateImageRequest defines model for UpdateImageRequest.
type UpdateImageRequest struct {
	// Name New name of the image.
	Name string `json:"name"`
}

// BadRequest Uniform error payload.
type BadRequest = Error

// InternalServerError Uniform error payload.
type InternalServerError = Error

// NotFound Uniform error payload.
type NotFound = Error

// Unavailable Uniform error payload.
type Unavailable = Error
