// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers_mocks

import (
	"context"
	"database/sql"

	"github.com/P3rCh1/immersive-images/backend/internal/dal/postgres"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// BeginTxx provides a mock function for the type MockDB
func (_mock *MockDB) BeginTxx(ctx context.Context, opts *sql.TxOptions) (context.Context, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTxx")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (context.Context, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) context.Context); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_BeginTxx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTxx'
type MockDB_BeginTxx_Call struct {
	*mock.Call
}

// BeginTxx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockDB_Expecter) BeginTxx(ctx any, opts any) *MockDB_BeginTxx_Call {
	return &MockDB_BeginTxx_Call{Call: _e.mock.On("BeginTxx", ctx, opts)}
}

func (_c *MockDB_BeginTxx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockDB_BeginTxx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.TxOptions
		if args[1] != nil {
			arg1 = args[1].(*sql.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_BeginTxx_Call) Return(context1 context.Context, err error) *MockDB_BeginTxx_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockDB_BeginTxx_Call) RunAndReturn(run func(ctx context.Context, opts *sql.TxOptions) (context.Context, error)) *MockDB_BeginTxx_Call {
	_c.Call.Return(run)
	return _c
}

// Beginx provides a mock function for the type MockDB
func (_mock *MockDB) Beginx(ctx context.Context) (context.Context, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Beginx")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_Beginx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Beginx'
type MockDB_Beginx_Call struct {
	*mock.Call
}

// Beginx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Beginx(ctx any) *MockDB_Beginx_Call {
	return &MockDB_Beginx_Call{Call: _e.mock.On("Beginx", ctx)}
}

func (_c *MockDB_Beginx_Call) Run(run func(ctx context.Context)) *MockDB_Beginx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDB_Beginx_Call) Return(context1 context.Context, err error) *MockDB_Beginx_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockDB_Beginx_Call) RunAndReturn(run func(ctx context.Context) (context.Context, error)) *MockDB_Beginx_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockDB
func (_mock *MockDB) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockDB_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Commit(ctx any) *MockDB_Commit_Call {
	return &MockDB_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockDB_Commit_Call) Run(run func(ctx context.Context)) *MockDB_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDB_Commit_Call) Return(err error) *MockDB_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockDB_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImage provides a mock function for the type MockDB
func (_mock *MockDB) CreateImage(ctx context.Context, image *postgres.Image) error {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *postgres.Image) error); ok {
		r0 = returnFunc(ctx, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_CreateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImage'
type MockDB_CreateImage_Call struct {
	*mock.Call
}

// CreateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image *postgres.Image
func (_e *MockDB_Expecter) CreateImage(ctx any, image any) *MockDB_CreateImage_Call {
	return &MockDB_CreateImage_Call{Call: _e.mock.On("CreateImage", ctx, image)}
}

func (_c *MockDB_CreateImage_Call) Run(run func(ctx context.Context, image *postgres.Image)) *MockDB_CreateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *postgres.Image
		if args[1] != nil {
			arg1 = args[1].(*postgres.Image)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_CreateImage_Call) Return(err error) *MockDB_CreateImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_CreateImage_Call) RunAndReturn(run func(ctx context.Context, image *postgres.Image) error) *MockDB_CreateImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockDB
func (_mock *MockDB) DeleteImage(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockDB_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDB_Expecter) DeleteImage(ctx any, id any) *MockDB_DeleteImage_Call {
	return &MockDB_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, id)}
}

func (_c *MockDB_DeleteImage_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDB_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_DeleteImage_Call) Return(err error) *MockDB_DeleteImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_DeleteImage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockDB_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImageForce provides a mock function for the type MockDB
func (_mock *MockDB) DeleteImageForce(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImageForce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_DeleteImageForce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImageForce'
type MockDB_DeleteImageForce_Call struct {
	*mock.Call
}

// DeleteImageForce is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDB_Expecter) DeleteImageForce(ctx any, id any) *MockDB_DeleteImageForce_Call {
	return &MockDB_DeleteImageForce_Call{Call: _e.mock.On("DeleteImageForce", ctx, id)}
}

func (_c *MockDB_DeleteImageForce_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDB_DeleteImageForce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_DeleteImageForce_Call) Return(err error) *MockDB_DeleteImageForce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_DeleteImageForce_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockDB_DeleteImageForce_Call {
	_c.Call.Return(run)
	return _c
}

// GetImage provides a mock function for the type MockDB
func (_mock *MockDB) GetImage(ctx context.Context, id uuid.UUID) (*postgres.Image, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 *postgres.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*postgres.Image, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *postgres.Image); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type MockDB_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDB_Expecter) GetImage(ctx any, id any) *MockDB_GetImage_Call {
	return &MockDB_GetImage_Call{Call: _e.mock.On("GetImage", ctx, id)}
}

func (_c *MockDB_GetImage_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDB_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_GetImage_Call) Return(image *postgres.Image, err error) *MockDB_GetImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockDB_GetImage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*postgres.Image, error)) *MockDB_GetImage_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockDB
func (_mock *MockDB) ListImages(ctx context.Context, limit int, start *uuid.UUID) ([]postgres.Image, error) {
	ret := _mock.Called(ctx, limit, start)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 []postgres.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *uuid.UUID) ([]postgres.Image, error)); ok {
		return returnFunc(ctx, limit, start)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *uuid.UUID) []postgres.Image); ok {
		r0 = returnFunc(ctx, limit, start)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, limit, start)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockDB_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - start *uuid.UUID
func (_e *MockDB_Expecter) ListImages(ctx any, limit any, start any) *MockDB_ListImages_Call {
	return &MockDB_ListImages_Call{Call: _e.mock.On("ListImages", ctx, limit, start)}
}

func (_c *MockDB_ListImages_Call) Run(run func(ctx context.Context, limit int, start *uuid.UUID)) *MockDB_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDB_ListImages_Call) Return(images []postgres.Image, err error) *MockDB_ListImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockDB_ListImages_Call) RunAndReturn(run func(ctx context.Context, limit int, start *uuid.UUID) ([]postgres.Image, error)) *MockDB_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockDB
func (_mock *MockDB) Rollback(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockDB_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockDB_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Rollback(ctx any) *MockDB_Rollback_Call {
	return &MockDB_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockDB_Rollback_Call) Run(run func(ctx context.Context)) *MockDB_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDB_Rollback_Call) Return() *MockDB_Rollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDB_Rollback_Call) RunAndReturn(run func(ctx context.Context)) *MockDB_Rollback_Call {
	_c.Run(run)
	return _c
}

// SetUploaded provides a mock function for the type MockDB
func (_mock *MockDB) SetUploaded(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetUploaded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_SetUploaded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUploaded'
type MockDB_SetUploaded_Call struct {
	*mock.Call
}

// SetUploaded is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDB_Expecter) SetUploaded(ctx any, id any) *MockDB_SetUploaded_Call {
	return &MockDB_SetUploaded_Call{Call: _e.mock.On("SetUploaded", ctx, id)}
}

func (_c *MockDB_SetUploaded_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDB_SetUploaded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_SetUploaded_Call) Return(err error) *MockDB_SetUploaded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_SetUploaded_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockDB_SetUploaded_Call {
	_c.Call.Return(run)
	return _c
}

// TotalImages provides a mock function for the type MockDB
func (_mock *MockDB) TotalImages(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TotalImages")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_TotalImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalImages'
type MockDB_TotalImages_Call struct {
	*mock.Call
}

// TotalImages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) TotalImages(ctx any) *MockDB_TotalImages_Call {
	return &MockDB_TotalImages_Call{Call: _e.mock.On("TotalImages", ctx)}
}

func (_c *MockDB_TotalImages_Call) Run(run func(ctx context.Context)) *MockDB_TotalImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDB_TotalImages_Call) Return(n int, err error) *MockDB_TotalImages_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDB_TotalImages_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockDB_TotalImages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImage provides a mock function for the type MockDB
func (_mock *MockDB) UpdateImage(ctx context.Context, image *postgres.Image) error {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *postgres.Image) error); ok {
		r0 = returnFunc(ctx, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_UpdateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImage'
type MockDB_UpdateImage_Call struct {
	*mock.Call
}

// UpdateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image *postgres.Image
func (_e *MockDB_Expecter) UpdateImage(ctx any, image any) *MockDB_UpdateImage_Call {
	return &MockDB_UpdateImage_Call{Call: _e.mock.On("UpdateImage", ctx, image)}
}

func (_c *MockDB_UpdateImage_Call) Run(run func(ctx context.Context, image *postgres.Image)) *MockDB_UpdateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *postgres.Image
		if args[1] != nil {
			arg1 = args[1].(*postgres.Image)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_UpdateImage_Call) Return(err error) *MockDB_UpdateImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_UpdateImage_Call) RunAndReturn(run func(ctx context.Context, image *postgres.Image) error) *MockDB_UpdateImage_Call {
	_c.Call.Return(run)
	return _c
}
