// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockS3 creates a new instance of MockS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3 {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockS3{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockS3 is an autogenerated mock type for the S3 type
type MockS3 struct {
	mock.Mock
}

type MockS3_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3) EXPECT() *MockS3_Expecter {
	return &MockS3_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockS3
func (_mock *MockS3) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockS3_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3_Expecter) Delete(ctx any, key any) *MockS3_Delete_Call {
	return &MockS3_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockS3_Delete_Call) Run(run func(ctx context.Context, key string)) *MockS3_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3_Delete_Call) Return(err error) *MockS3_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockS3_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockS3
func (_mock *MockS3) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockS3_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3_Expecter) Get(ctx any, key any) *MockS3_Get_Call {
	return &MockS3_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockS3_Get_Call) Run(run func(ctx context.Context, key string)) *MockS3_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3_Get_Call) Return(bytes []byte, err error) *MockS3_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockS3_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockS3_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockS3
func (_mock *MockS3) Upload(ctx context.Context, objectKey string, data []byte) error {
	ret := _mock.Called(ctx, objectKey, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, objectKey, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockS3_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - data []byte
func (_e *MockS3_Expecter) Upload(ctx any, objectKey any, data any) *MockS3_Upload_Call {
	return &MockS3_Upload_Call{Call: _e.mock.On("Upload", ctx, objectKey, data)}
}

func (_c *MockS3_Upload_Call) Run(run func(ctx context.Context, objectKey string, data []byte)) *MockS3_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockS3_Upload_Call) Return(err error) *MockS3_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Upload_Call) RunAndReturn(run func(ctx context.Context, objectKey string, data []byte) error) *MockS3_Upload_Call {
	_c.Call.Return(run)
	return _c
}
