name: Backend CI

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
  pull_request:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Run acceptance tests
        run: make acc-tests

  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod

      - name: Run golangci-lint
        run: make golangci-lint
